/**********************authContext******************* */
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const USER_LOADED = "USER_LOADED";
export const LOGOUT = "LOGOUT";

/**********************UserContext******************* */
export const UPDATE_IMAGE = "UPDATE_IMAGE";
export const SEND_DEMANDEANNONCEUR = "SEND_DEMANDEANNONCEUR";
export const ADD_CENTREOFINTERET = "ADD_CENTREOFINTERET";
export const DELETE_CENTREOFINTERET = "DELETE_CENTREOFINTERET";
export const UPDATE_DESCRIPTION = "UPDATE_DESCRIPTION";
export const REMOVE_RSPONSEMESSAGE = "REMOVE_RSPONSEMESSAGE";
export const LOAD_ANNONCEUR = "LOAD_ANNONCEUR";
export const UPDATE_ANNONCEURPICTURE = "UPDATE_ANNONCEURPICTURE";
export const UPDATE_ANNONCEURINFO = "UPDATE_ANNONCEURINFO";
export const LOAD_CATEGORIE = "LOAD_CATEGORIE";

/**********************pubContext******************* */
export const GET_ACTIVITYORGANIZED = "GET_ACTIVITY";
export const GET_ACTIVITYPARTICIPATED = "GET_ACTIVITYPARTICIPATED";

export const ADD_ACTIVITY = "ADD_ACTIVITY";
export const EDIT_PUB = "EDIT_PUB";
export const ADD_EVENT = "ADD_EVENT";
export const ADD_ANNONCE = "ADD_ANNONCE";
export const DELETE_PUBLICATION = "DELETE_PUBLICATION";
export const GET_ANNONCEUREVENT = "GET_ANNONCEUREVENT";
export const GET_ANNONCEURANNONCE = "GET_ANNONCEURANNONCE";
export const GET_PARTICIPANTDATA = "GET_PARTICIPANTDATA";
export const REMOVE_PARTICIPANTDATA = "REMOVE_PARTICIPANTDATA";
export const REMOVE_PUBRSPONSEMESSAGE = "REMOVE_PUBRSPONSEMESSAGE";
export const CLEAR_ANNONCEURPUBS = "CLEAR_ANNONCEURPUBS";
export const CLEAR_ABONNÉPUB = "CLEAR_ABONNÉPUB";
